# Generated by Django 3.2.8 on 2021-10-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonorForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=30)),
                ('BirthDate', models.DateField()),
                ('NIK', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='NamaLayanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=20)),
                ('Province', models.CharField(max_length=20)),
                ('Telephone', models.CharField(max_length=13)),
                ('Email', models.EmailField(max_length=254)),
                ('Website', models.URLField()),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('About', models.TextField()),
                ('Why1', models.TextField(max_length=11)),
                ('Why2', models.TextField(max_length=11)),
                ('Why3', models.TextField(max_length=11)),
                ('Why4', models.TextField(max_length=11)),
                ('Syarat1', models.CharField(max_length=30)),
                ('Syarat2', models.CharField(max_length=30)),
                ('Syarat3', models.CharField(max_length=30)),
                ('Syarat4', models.CharField(max_length=30)),
                ('Syarat5', models.CharField(max_length=30)),
            ],
        ),
    ]
