# Generated by Django 3.2.8 on 2021-10-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorform',
            name='Goldar',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], default=3, max_length=3),
        ),
        migrations.AlterField(
            model_name='namalayanan',
            name='Syarat1',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='namalayanan',
            name='Syarat2',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='namalayanan',
            name='Syarat3',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='namalayanan',
            name='Syarat4',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='namalayanan',
            name='Syarat5',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='namalayanan',
            name='Why1',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='namalayanan',
            name='Why2',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='namalayanan',
            name='Why3',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='namalayanan',
            name='Why4',
            field=models.TextField(max_length=300),
        ),
    ]
