# Generated by Django 3.2.8 on 2021-10-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211030_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='namalayanan',
            name='Img',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AlterField(
            model_name='donorform',
            name='BirthDate',
            field=models.DateField(verbose_name='Tanggal Lahir'),
        ),
        migrations.AlterField(
            model_name='donorform',
            name='FullName',
            field=models.CharField(max_length=30, verbose_name='Nama Lengkap'),
        ),
        migrations.AlterField(
            model_name='donorform',
            name='Goldar',
            field=models.CharField(choices=[('Pilih', 'Pilih'), ('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], default=1, max_length=5, verbose_name='Golongan Darah'),
        ),
        migrations.AlterField(
            model_name='donorform',
            name='NIK',
            field=models.CharField(max_length=15, verbose_name='Nomor Induk Kependudukan (NIK)'),
        ),
    ]
