# Generated by Django 3.2.8 on 2021-10-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211031_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namalayanan',
            name='Img',
            field=models.ImageField(default=1, upload_to='main/img/'),
        ),
    ]
