# Generated by Django 3.2.8 on 2021-11-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_namalayanan_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Province', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='namalayanan',
            name='Img',
            field=models.ImageField(default='image.jpg', upload_to='main/img/'),
        ),
    ]
