# Generated by Django 3.2.8 on 2021-11-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211104_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='namalayanan',
            name='Goldar',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], default=1, max_length=2, verbose_name='Golongan Darah'),
        ),
        migrations.AddField(
            model_name='namalayanan',
            name='Status',
            field=models.CharField(choices=[('Pernah Terjangkit', 'Pernah Terjangkit'), ('Tidak Pernah Terjangkit', 'Tidak Pernah Terjangkit'), ('Sedang Terjangkit', 'Sedang Terjangkit')], default=1, max_length=50, verbose_name='Status Terjangkit'),
        ),
    ]
