# Generated by Django 3.2.8 on 2021-11-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211104_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='Goldar',
            field=models.CharField(default=1, max_length=5),
        ),
    ]
