# Generated by Django 3.2.8 on 2021-11-04 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_filter_goldar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namalayanan',
            name='Status',
        ),
    ]
