# Generated by Django 3.2.8 on 2021-11-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_namalayanan_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
