# Generated by Django 3.2.8 on 2021-11-04 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20211104_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namalayanan',
            name='About',
        ),
        migrations.RemoveField(
            model_name='namalayanan',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='namalayanan',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='namalayanan',
            name='Img',
        ),
        migrations.RemoveField(
            model_name='namalayanan',
            name='Syarat1',
        ),
        migrations.RemoveField(
            model_name='namalayanan',
            name='Syarat2',
        ),
        migrations.RemoveField(
            model_name='namalayanan',
            name='Syarat3',
        ),
        migrations.RemoveField(
            model_name='namalayanan',
            name='Syarat4',
        ),
        migrations.RemoveField(
            model_name='namalayanan',
            name='Syarat5',
        ),
        migrations.RemoveField(
            model_name='namalayanan',
            name='Telephone',
        ),
        migrations.RemoveField(
            model_name='namalayanan',
            name='Time',
        ),
        migrations.RemoveField(
            model_name='namalayanan',
            name='Website',
        ),
        migrations.RemoveField(
            model_name='namalayanan',
            name='Why1',
        ),
        migrations.RemoveField(
            model_name='namalayanan',
            name='Why2',
        ),
        migrations.RemoveField(
            model_name='namalayanan',
            name='Why3',
        ),
        migrations.RemoveField(
            model_name='namalayanan',
            name='Why4',
        ),
        migrations.AddField(
            model_name='relawandonor',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Donor Darah'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relawandonor',
            name='Sentra',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='Sentra Layanan Donor Darah'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relawandonor',
            name='Time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Waktu Donor Darah'),
            preserve_default=False,
        ),
    ]
