# Generated by Django 3.2.8 on 2021-11-04 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211104_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relawandonor',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='relawandonor',
            name='Sentra',
        ),
        migrations.RemoveField(
            model_name='relawandonor',
            name='Time',
        ),
        migrations.AddField(
            model_name='donorform',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Donor Darah'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donorform',
            name='Sentra',
            field=models.CharField(default='', max_length=30, verbose_name='Sentra Layanan Donor Darah'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donorform',
            name='Time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Waktu Donor Darah'),
            preserve_default=False,
        ),
    ]
