# Generated by Django 3.2.8 on 2021-11-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20211104_2224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelawanDonor',
        ),
        migrations.AddField(
            model_name='namalayanan',
            name='Number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donorform',
            name='NIK',
            field=models.IntegerField(max_length=16, verbose_name='Nomor Induk Kependudukan (NIK)'),
        ),
    ]
